//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyThuCung.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class ThuCungEntities : DbContext
    {
        public ThuCungEntities()
            : base("name=ThuCungEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Contract_Sell> Contract_Sell { get; set; }
        public virtual DbSet<Contract_Ser> Contract_Ser { get; set; }
        public virtual DbSet<Customer> Customers { get; set; }
        public virtual DbSet<Employee> Employees { get; set; }
        public virtual DbSet<Pet> Pets { get; set; }
        public virtual DbSet<Servic> Servics { get; set; }
        public virtual DbSet<Species> Species { get; set; }
        public virtual DbSet<Supplier> Suppliers { get; set; }
        public virtual DbSet<User> Users { get; set; }
        public virtual DbSet<WarrantyType> WarrantyTypes { get; set; }
        public virtual DbSet<view_HDDichVu> view_HDDichVu { get; set; }
        public virtual DbSet<view_HDThuCung> view_HDThuCung { get; set; }
    
        public virtual int delete_contractSell(Nullable<int> id)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("delete_contractSell", idParameter);
        }
    
        public virtual int delete_contractSer(Nullable<int> id)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("delete_contractSer", idParameter);
        }
    
        public virtual ObjectResult<GetData_contractSell_Result> GetData_contractSell()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetData_contractSell_Result>("GetData_contractSell");
        }
    
        public virtual ObjectResult<GetData_contractSer_Result> GetData_contractSer()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetData_contractSer_Result>("GetData_contractSer");
        }
    
        public virtual int insert_contractSell(string name_NV, string name_Customer, Nullable<int> iD_pet, string name_warr, Nullable<System.DateTime> dateSell, Nullable<int> price)
        {
            var name_NVParameter = name_NV != null ?
                new ObjectParameter("Name_NV", name_NV) :
                new ObjectParameter("Name_NV", typeof(string));
    
            var name_CustomerParameter = name_Customer != null ?
                new ObjectParameter("Name_Customer", name_Customer) :
                new ObjectParameter("Name_Customer", typeof(string));
    
            var iD_petParameter = iD_pet.HasValue ?
                new ObjectParameter("ID_pet", iD_pet) :
                new ObjectParameter("ID_pet", typeof(int));
    
            var name_warrParameter = name_warr != null ?
                new ObjectParameter("Name_warr", name_warr) :
                new ObjectParameter("Name_warr", typeof(string));
    
            var dateSellParameter = dateSell.HasValue ?
                new ObjectParameter("DateSell", dateSell) :
                new ObjectParameter("DateSell", typeof(System.DateTime));
    
            var priceParameter = price.HasValue ?
                new ObjectParameter("Price", price) :
                new ObjectParameter("Price", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("insert_contractSell", name_NVParameter, name_CustomerParameter, iD_petParameter, name_warrParameter, dateSellParameter, priceParameter);
        }
    
        public virtual int insert_contractSer(string nameEmp, string nameCus, Nullable<System.DateTime> dateBuy, string nameSer)
        {
            var nameEmpParameter = nameEmp != null ?
                new ObjectParameter("NameEmp", nameEmp) :
                new ObjectParameter("NameEmp", typeof(string));
    
            var nameCusParameter = nameCus != null ?
                new ObjectParameter("NameCus", nameCus) :
                new ObjectParameter("NameCus", typeof(string));
    
            var dateBuyParameter = dateBuy.HasValue ?
                new ObjectParameter("DateBuy", dateBuy) :
                new ObjectParameter("DateBuy", typeof(System.DateTime));
    
            var nameSerParameter = nameSer != null ?
                new ObjectParameter("NameSer", nameSer) :
                new ObjectParameter("NameSer", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("insert_contractSer", nameEmpParameter, nameCusParameter, dateBuyParameter, nameSerParameter);
        }
    
        public virtual ObjectResult<timKiemHDBanThuCung_Result> timKiemHDBanThuCung(Nullable<int> day, Nullable<int> month, Nullable<int> year)
        {
            var dayParameter = day.HasValue ?
                new ObjectParameter("day", day) :
                new ObjectParameter("day", typeof(int));
    
            var monthParameter = month.HasValue ?
                new ObjectParameter("month", month) :
                new ObjectParameter("month", typeof(int));
    
            var yearParameter = year.HasValue ?
                new ObjectParameter("year", year) :
                new ObjectParameter("year", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<timKiemHDBanThuCung_Result>("timKiemHDBanThuCung", dayParameter, monthParameter, yearParameter);
        }
    
        public virtual ObjectResult<timKiemHDDV_Result> timKiemHDDV(Nullable<int> day, Nullable<int> month, Nullable<int> year)
        {
            var dayParameter = day.HasValue ?
                new ObjectParameter("day", day) :
                new ObjectParameter("day", typeof(int));
    
            var monthParameter = month.HasValue ?
                new ObjectParameter("month", month) :
                new ObjectParameter("month", typeof(int));
    
            var yearParameter = year.HasValue ?
                new ObjectParameter("year", year) :
                new ObjectParameter("year", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<timKiemHDDV_Result>("timKiemHDDV", dayParameter, monthParameter, yearParameter);
        }
    
        public virtual int update_contractSell(Nullable<int> id, string name_NV, string name_Customer, Nullable<int> iD_pet, string name_warr, Nullable<System.DateTime> dateSell, Nullable<int> price)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            var name_NVParameter = name_NV != null ?
                new ObjectParameter("Name_NV", name_NV) :
                new ObjectParameter("Name_NV", typeof(string));
    
            var name_CustomerParameter = name_Customer != null ?
                new ObjectParameter("Name_Customer", name_Customer) :
                new ObjectParameter("Name_Customer", typeof(string));
    
            var iD_petParameter = iD_pet.HasValue ?
                new ObjectParameter("ID_pet", iD_pet) :
                new ObjectParameter("ID_pet", typeof(int));
    
            var name_warrParameter = name_warr != null ?
                new ObjectParameter("Name_warr", name_warr) :
                new ObjectParameter("Name_warr", typeof(string));
    
            var dateSellParameter = dateSell.HasValue ?
                new ObjectParameter("DateSell", dateSell) :
                new ObjectParameter("DateSell", typeof(System.DateTime));
    
            var priceParameter = price.HasValue ?
                new ObjectParameter("Price", price) :
                new ObjectParameter("Price", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("update_contractSell", idParameter, name_NVParameter, name_CustomerParameter, iD_petParameter, name_warrParameter, dateSellParameter, priceParameter);
        }
    
        public virtual int update_contractSer(Nullable<int> id, string nameEmp, string nameCus, Nullable<System.DateTime> dateBuy, string nameSer)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            var nameEmpParameter = nameEmp != null ?
                new ObjectParameter("NameEmp", nameEmp) :
                new ObjectParameter("NameEmp", typeof(string));
    
            var nameCusParameter = nameCus != null ?
                new ObjectParameter("NameCus", nameCus) :
                new ObjectParameter("NameCus", typeof(string));
    
            var dateBuyParameter = dateBuy.HasValue ?
                new ObjectParameter("DateBuy", dateBuy) :
                new ObjectParameter("DateBuy", typeof(System.DateTime));
    
            var nameSerParameter = nameSer != null ?
                new ObjectParameter("NameSer", nameSer) :
                new ObjectParameter("NameSer", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("update_contractSer", idParameter, nameEmpParameter, nameCusParameter, dateBuyParameter, nameSerParameter);
        }
    
        public virtual ObjectResult<usp_GetContractSellTheoThangVaNam_Result> usp_GetContractSellTheoThangVaNam(Nullable<int> month, Nullable<int> year)
        {
            var monthParameter = month.HasValue ?
                new ObjectParameter("month", month) :
                new ObjectParameter("month", typeof(int));
    
            var yearParameter = year.HasValue ?
                new ObjectParameter("year", year) :
                new ObjectParameter("year", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_GetContractSellTheoThangVaNam_Result>("usp_GetContractSellTheoThangVaNam", monthParameter, yearParameter);
        }
    
        public virtual ObjectResult<usp_GetContractSerTheoThangVaNam_Result> usp_GetContractSerTheoThangVaNam(Nullable<int> month, Nullable<int> year)
        {
            var monthParameter = month.HasValue ?
                new ObjectParameter("month", month) :
                new ObjectParameter("month", typeof(int));
    
            var yearParameter = year.HasValue ?
                new ObjectParameter("year", year) :
                new ObjectParameter("year", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_GetContractSerTheoThangVaNam_Result>("usp_GetContractSerTheoThangVaNam", monthParameter, yearParameter);
        }
    
        public virtual ObjectResult<usp_GetDanhSachDichVuDaMua_Result> usp_GetDanhSachDichVuDaMua(Nullable<int> idkh)
        {
            var idkhParameter = idkh.HasValue ?
                new ObjectParameter("idkh", idkh) :
                new ObjectParameter("idkh", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_GetDanhSachDichVuDaMua_Result>("usp_GetDanhSachDichVuDaMua", idkhParameter);
        }
    
        public virtual ObjectResult<usp_GetDataBaoHanh_Result> usp_GetDataBaoHanh()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_GetDataBaoHanh_Result>("usp_GetDataBaoHanh");
        }
    
        public virtual ObjectResult<usp_GetDataCustomer_Result> usp_GetDataCustomer()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_GetDataCustomer_Result>("usp_GetDataCustomer");
        }
    
        public virtual ObjectResult<usp_GetDataDichVu_Result> usp_GetDataDichVu()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_GetDataDichVu_Result>("usp_GetDataDichVu");
        }
    
        public virtual ObjectResult<usp_GetDataHDBanDV_Result> usp_GetDataHDBanDV()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_GetDataHDBanDV_Result>("usp_GetDataHDBanDV");
        }
    
        public virtual ObjectResult<usp_GetDataHDBanThuCung_Result> usp_GetDataHDBanThuCung()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_GetDataHDBanThuCung_Result>("usp_GetDataHDBanThuCung");
        }
    
        public virtual ObjectResult<usp_GetDataNhaCungCap_Result> usp_GetDataNhaCungCap()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_GetDataNhaCungCap_Result>("usp_GetDataNhaCungCap");
        }
    
        public virtual ObjectResult<usp_GetDataNV_Result> usp_GetDataNV()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_GetDataNV_Result>("usp_GetDataNV");
        }
    
        public virtual ObjectResult<usp_GetDataUser_Result> usp_GetDataUser()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_GetDataUser_Result>("usp_GetDataUser");
        }
    
        public virtual ObjectResult<usp_GetLoaiThuCung_Result> usp_GetLoaiThuCung()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_GetLoaiThuCung_Result>("usp_GetLoaiThuCung");
        }
    
        public virtual int usp_GetProfitContractSellTheoThangVaNam(Nullable<int> month, Nullable<int> year, ObjectParameter total)
        {
            var monthParameter = month.HasValue ?
                new ObjectParameter("month", month) :
                new ObjectParameter("month", typeof(int));
    
            var yearParameter = year.HasValue ?
                new ObjectParameter("year", year) :
                new ObjectParameter("year", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("usp_GetProfitContractSellTheoThangVaNam", monthParameter, yearParameter, total);
        }
    
        public virtual int usp_GetSumSalaryOfEmp(ObjectParameter total)
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("usp_GetSumSalaryOfEmp", total);
        }
    
        public virtual ObjectResult<usp_GetThuCung_Result> usp_GetThuCung()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_GetThuCung_Result>("usp_GetThuCung");
        }
    
        public virtual ObjectResult<usp_GetThuCungChuaBan_Result> usp_GetThuCungChuaBan()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_GetThuCungChuaBan_Result>("usp_GetThuCungChuaBan");
        }
    
        public virtual ObjectResult<usp_GetThuCungChuaBanTheoGioiTinh_Result> usp_GetThuCungChuaBanTheoGioiTinh(string sex)
        {
            var sexParameter = sex != null ?
                new ObjectParameter("sex", sex) :
                new ObjectParameter("sex", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_GetThuCungChuaBanTheoGioiTinh_Result>("usp_GetThuCungChuaBanTheoGioiTinh", sexParameter);
        }
    
        public virtual ObjectResult<usp_GetThuCungChuaBanTheoLoai_Result> usp_GetThuCungChuaBanTheoLoai(string tenloai)
        {
            var tenloaiParameter = tenloai != null ?
                new ObjectParameter("tenloai", tenloai) :
                new ObjectParameter("tenloai", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_GetThuCungChuaBanTheoLoai_Result>("usp_GetThuCungChuaBanTheoLoai", tenloaiParameter);
        }
    
        public virtual ObjectResult<usp_GetThuCungChuaBanTheoTuoi_Result> usp_GetThuCungChuaBanTheoTuoi(Nullable<int> age)
        {
            var ageParameter = age.HasValue ?
                new ObjectParameter("age", age) :
                new ObjectParameter("age", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_GetThuCungChuaBanTheoTuoi_Result>("usp_GetThuCungChuaBanTheoTuoi", ageParameter);
        }
    
        public virtual ObjectResult<usp_GetThuCungDaMua_Result> usp_GetThuCungDaMua(Nullable<int> idkh)
        {
            var idkhParameter = idkh.HasValue ?
                new ObjectParameter("idkh", idkh) :
                new ObjectParameter("idkh", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_GetThuCungDaMua_Result>("usp_GetThuCungDaMua", idkhParameter);
        }
    
        public virtual int usp_GetTotalMoneyTransactionContractSellTheoThangVaNam(Nullable<int> month, Nullable<int> year, ObjectParameter total)
        {
            var monthParameter = month.HasValue ?
                new ObjectParameter("month", month) :
                new ObjectParameter("month", typeof(int));
    
            var yearParameter = year.HasValue ?
                new ObjectParameter("year", year) :
                new ObjectParameter("year", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("usp_GetTotalMoneyTransactionContractSellTheoThangVaNam", monthParameter, yearParameter, total);
        }
    
        public virtual int usp_GetTotalMoneyTransactionContractSerTheoThangVaNam(Nullable<int> month, Nullable<int> year, ObjectParameter total)
        {
            var monthParameter = month.HasValue ?
                new ObjectParameter("month", month) :
                new ObjectParameter("month", typeof(int));
    
            var yearParameter = year.HasValue ?
                new ObjectParameter("year", year) :
                new ObjectParameter("year", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("usp_GetTotalMoneyTransactionContractSerTheoThangVaNam", monthParameter, yearParameter, total);
        }
    
        public virtual ObjectResult<usp_TimDVTheoTen_Result> usp_TimDVTheoTen(string name)
        {
            var nameParameter = name != null ?
                new ObjectParameter("name", name) :
                new ObjectParameter("name", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_TimDVTheoTen_Result>("usp_TimDVTheoTen", nameParameter);
        }
    
        public virtual ObjectResult<usp_TimKHTheoSDT_Result> usp_TimKHTheoSDT(string sdt)
        {
            var sdtParameter = sdt != null ?
                new ObjectParameter("sdt", sdt) :
                new ObjectParameter("sdt", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_TimKHTheoSDT_Result>("usp_TimKHTheoSDT", sdtParameter);
        }
    
        public virtual ObjectResult<usp_TimKHTheoTen_Result> usp_TimKHTheoTen(string name)
        {
            var nameParameter = name != null ?
                new ObjectParameter("name", name) :
                new ObjectParameter("name", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_TimKHTheoTen_Result>("usp_TimKHTheoTen", nameParameter);
        }
    
        public virtual ObjectResult<usp_TimKHTheoTuoi_Result> usp_TimKHTheoTuoi(Nullable<int> age)
        {
            var ageParameter = age.HasValue ?
                new ObjectParameter("age", age) :
                new ObjectParameter("age", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_TimKHTheoTuoi_Result>("usp_TimKHTheoTuoi", ageParameter);
        }
    
        public virtual ObjectResult<usp_TimNVTheoLuong_Result> usp_TimNVTheoLuong(Nullable<int> salary)
        {
            var salaryParameter = salary.HasValue ?
                new ObjectParameter("salary", salary) :
                new ObjectParameter("salary", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_TimNVTheoLuong_Result>("usp_TimNVTheoLuong", salaryParameter);
        }
    
        public virtual ObjectResult<usp_TimNVTheoSDT_Result> usp_TimNVTheoSDT(string sdt)
        {
            var sdtParameter = sdt != null ?
                new ObjectParameter("sdt", sdt) :
                new ObjectParameter("sdt", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_TimNVTheoSDT_Result>("usp_TimNVTheoSDT", sdtParameter);
        }
    
        public virtual ObjectResult<usp_TimNVTheoTen_Result> usp_TimNVTheoTen(string name)
        {
            var nameParameter = name != null ?
                new ObjectParameter("name", name) :
                new ObjectParameter("name", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_TimNVTheoTen_Result>("usp_TimNVTheoTen", nameParameter);
        }
    
        public virtual ObjectResult<usp_TimNVTheoTuoi_Result> usp_TimNVTheoTuoi(Nullable<int> age)
        {
            var ageParameter = age.HasValue ?
                new ObjectParameter("age", age) :
                new ObjectParameter("age", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_TimNVTheoTuoi_Result>("usp_TimNVTheoTuoi", ageParameter);
        }
    
        public virtual ObjectResult<usp_TimTCTheoGioiTinh_Result> usp_TimTCTheoGioiTinh(string sex)
        {
            var sexParameter = sex != null ?
                new ObjectParameter("sex", sex) :
                new ObjectParameter("sex", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_TimTCTheoGioiTinh_Result>("usp_TimTCTheoGioiTinh", sexParameter);
        }
    
        public virtual ObjectResult<usp_TimTCTheoLoai_Result> usp_TimTCTheoLoai(Nullable<int> loai)
        {
            var loaiParameter = loai.HasValue ?
                new ObjectParameter("loai", loai) :
                new ObjectParameter("loai", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_TimTCTheoLoai_Result>("usp_TimTCTheoLoai", loaiParameter);
        }
    
        public virtual ObjectResult<usp_TimTCTheoTuoi_Result> usp_TimTCTheoTuoi(Nullable<int> tuoi)
        {
            var tuoiParameter = tuoi.HasValue ?
                new ObjectParameter("tuoi", tuoi) :
                new ObjectParameter("tuoi", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_TimTCTheoTuoi_Result>("usp_TimTCTheoTuoi", tuoiParameter);
        }
    
        public virtual ObjectResult<usp_TimUserTheoTen_Result> usp_TimUserTheoTen(string name)
        {
            var nameParameter = name != null ?
                new ObjectParameter("name", name) :
                new ObjectParameter("name", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_TimUserTheoTen_Result>("usp_TimUserTheoTen", nameParameter);
        }
    
        public virtual ObjectResult<usp_TimUserTheoUsername_Result> usp_TimUserTheoUsername(string name)
        {
            var nameParameter = name != null ?
                new ObjectParameter("name", name) :
                new ObjectParameter("name", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_TimUserTheoUsername_Result>("usp_TimUserTheoUsername", nameParameter);
        }
    }
}
