//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyThuCung.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class view_HDDichVu
    {
        public int ID_ConSer { get; set; }
        public Nullable<int> ID_Emp { get; set; }
        public Nullable<int> ID_Cus { get; set; }
        public Nullable<System.DateTime> DateBuy { get; set; }
        public Nullable<int> ID_Ser { get; set; }
        public string Name { get; set; }
        public Nullable<int> Price { get; set; }
    }
}
