//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyThuCung.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class WarrantyType
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public WarrantyType()
        {
            this.Contract_Sell = new HashSet<Contract_Sell>();
        }
    
        public int ID_Warr { get; set; }
        public string Name { get; set; }
        public string Months { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Contract_Sell> Contract_Sell { get; set; }
    }
}
